mongo:
  link_acesso: 'Link aqui'
  database: 'Nome do banco'
  collection_dos_associados: 'associados'
  collection_dos_em_analise: 'em_analise'

servidor:
  nome: 'Servidorzim'
  prefix: '&b[Discord]'
  sucesso: '&aMuito bem! Agora envie sua token para o privado do bot SeuBot#0000'